spring:
#  security:
#    user:#      name: user
#      password: 12345
  messages:
    basename: locale/message/message
    encoding: UTF-8
#    cache-duration: 3600
  datasource: 
   url: jdbc:postgresql://localhost:5432/postgres
   username: postgres
   password: jasper840831
   driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:      ddl-auto: update
    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:    cache: false
    encoding: UTF-8

server:
  port : 5000 # aws啟動端口號

placeholder:
  hello:
    visiter: message.hello.visiter
    username: message.hello.username